services:
  - type: web
    name: tienda-telas
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # <-- Cambiado de quincorn a gunicorn
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: SECRET_KEY
        generateValue: true